# Generated by Django 3.2.3 on 2021-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldsrelatedonetoonefield', unique=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True),
        ),
    ]
