# Generated by Django 3.2.3 on 2021-06-17 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210610_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogger',
            name='is_blogger',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as blogger on site.'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as site staff.'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='is_viewer',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as viewer sitef.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pic1',
            field=models.ImageField(default='noimage.jpg', upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
