# Generated by Django 3.2.3 on 2021-06-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210603_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='DOB',
            field=models.DateField(),
        ),
    ]
