# Generated by Django 3.2.3 on 2021-06-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogger_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='DOB',
        ),
    ]
