# Generated by Django 3.2.3 on 2021-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogger_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='user_pic',
            field=models.ImageField(default='user/profil.png', height_field='500px', upload_to='user/', width_field='350px'),
        ),
    ]
