# Generated by Django 3.2.3 on 2021-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogger_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
