# Generated by Django 3.2.3 on 2021-06-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogger_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
