# Generated by Django 3.2.3 on 2021-06-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_delete_usernew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categorie',
        ),
        migrations.AddField(
            model_name='blog',
            name='categ',
            field=models.ManyToManyField(to='blog.Categories'),
        ),
    ]
