# Generated by Django 3.2.3 on 2021-06-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210604_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categ',
        ),
        migrations.AddField(
            model_name='blog',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categories'),
        ),
    ]
