# Generated by Django 3.2.3 on 2021-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210604_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categorie',
        ),
        migrations.AddField(
            model_name='blog',
            name='categorie',
            field=models.ManyToManyField(to='blog.Categories'),
        ),
    ]
